#!/usr/bin/env python3
"""Generates the data flow diagram (docs/dataflow.svg and docs/dataflow-annotated.svg).

Standard library only, matching the rest of this project. Everything about
the diagram's *content* lives in the CONFIG block below: sources, pipeline
stages, outputs, site pages and (for the annotated variant) the load-bearing
rules called out per stage. Edit that block and rerun; the layout code that
follows measures and positions everything from it.

    python3 tools/make_dataflow_diagram.py            # writes both variants
    python3 tools/make_dataflow_diagram.py --mode basic
    python3 tools/make_dataflow_diagram.py --mode annotated
"""

import argparse
import textwrap
from pathlib import Path

# ---------------------------------------------------------------------------
# CONFIG — the only section that should need editing when the data changes
# ---------------------------------------------------------------------------

TITLE = "NYC Hazard Historian — Data Flow"
SUBTITLE = (
    "Federal and city source records, through a five-stage pipeline, "
    "into a filterable event archive"
)

SOURCES = [
    {"name": "NOAA Storm Events", "grain": "Event type, place, window"},
    {"name": "GHCN Daily", "grain": "Station, day — Central Park since 1869"},
    {"name": "NOAA CO-OPS", "grain": "Station, six minutes — tides"},
    {"name": "IEM Radar", "grain": "Radar tile, five minutes", "bypass": True},
    {"name": "HURDAT2", "grain": "Storm, six hours — best track"},
    {"name": "OpenFEMA", "grain": "Project, claim, disaster"},
    {"name": "NYC Open Data", "grain": "311 requests + collisions"},
    {"name": "BLS CPI-U", "grain": "Month — inflation index"},
]

CONFIG_STAGE = {
    "id": "00",
    "name": "config.py",
    "desc": "Every tunable value: source URLs, the zone map, the hazard "
    "vocabulary, validation thresholds, hand-declared event merges.",
}

STAGES = [
    {
        "id": "01",
        "name": "fetch",
        "desc": "Downloads each source and checks what arrived.",
        "rule": "Catches an HTML error page masquerading as HTTP 200.",
    },
    {
        "id": "02",
        "name": "normalize",
        "desc": "Builds event_rows, events, weather, tracks.",
        "rule": "Joins on codes, never on names.",
    },
    {
        "id": "03",
        "name": "enrich",
        "desc": "Attaches 311, collisions, water levels, FEMA aid.",
        "rule": "The only stage that returns to the network.",
    },
    {
        "id": "04",
        "name": "validate",
        "desc": "Checks grains and referential integrity both ways.",
        "rule": "Fails, rather than warns, on a wrong figure.",
    },
    {
        "id": "05",
        "name": "export",
        "desc": "Writes site JSON + CSV, moves them into place.",
        "rule": "Refuses to run if validation did not pass.",
    },
]

OUTPUTS = [
    {"name": "docs/data/*.json", "desc": "~900 events, one index file"},
    {"name": "docs/downloads/*.csv", "desc": "Nominal and CPI-adjusted, both bases"},
]

CROSSCUTTING = [
    "Every measure carries a status — ok / not_collected / withheld / "
    "not_applicable — never a bare zero.",
    "Derived figures, like storm surge and event peaks, are labeled as "
    "derived everywhere they appear.",
]

SITE_PAGES = [
    {"name": "Explorer", "desc": "Filters ~900 events client-side; state lives in the URL"},
    {"name": "Event page", "desc": "One file per event, loaded only when opened"},
    {"name": "Compare", "desc": "Cross-event comparison"},
    {"name": "Downloads", "desc": "Public CSV, served as-is"},
    {"name": "Radar overlay", "desc": "Composite reflectivity over MapLibre GL", "bypass": True},
]

BYPASS_LABEL = "fetched live in the browser — bypasses the pipeline"

FOOTNOTE = (
    "Generated by tools/make_dataflow_diagram.py from the CONFIG block at its "
    "top — edit that, then rerun, to update this diagram."
)

# ---------------------------------------------------------------------------
# Style
# ---------------------------------------------------------------------------

FONT = "-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif"
INK = "#1f2933"
SUBINK = "#52606d"
RULE_COLOR = "#9a5b13"
LINE = "#9aa5b1"
BG = "#fbfaf7"

BAND_STYLES = {
    "sources": {"fill": "#eef3f8", "stroke": "#9db4c9", "label": "Sources"},
    "pipeline": {"fill": "#fbf1e4", "stroke": "#d8a866", "label": "pipeline/"},
    "outputs": {"fill": "#e9f5f0", "stroke": "#8fc2a8", "label": "Outputs"},
    "site": {"fill": "#f1edf7", "stroke": "#b3a0d1", "label": "Site (docs/*.html)"},
}

W = 1600
MARGIN = 56
CONTENT_W = W - 2 * MARGIN

# ---------------------------------------------------------------------------
# Small SVG helpers
# ---------------------------------------------------------------------------


def esc(s):
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def wrap(text, width_px, font_size, bold=False):
    avg_char = font_size * (0.62 if bold else 0.55)
    chars = max(6, int(width_px / avg_char))
    return textwrap.wrap(text, chars) or [""]


def text_block(x, y, lines, size, fill, weight="normal", anchor="middle", italic=False, line_h=None):
    line_h = line_h or size * 1.35
    style = f"font: {'italic ' if italic else ''}{weight} {size}px {FONT}; fill: {fill};"
    out = [f'<text x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}" style="{style}">']
    for i, line in enumerate(lines):
        dy = 0 if i == 0 else line_h
        out.append(f'<tspan x="{x:.1f}" dy="{dy:.1f}">{esc(line)}</tspan>')
    out.append("</text>")
    return "".join(out), line_h * len(lines)


def rrect(x, y, w, h, r, fill, stroke, sw=1.5, dash=None):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    return (
        f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="{r}" '
        f'fill="{fill}" stroke="{stroke}" stroke-width="{sw}"{d}/>'
    )


def line(x1, y1, x2, y2, stroke=LINE, sw=1.6, dash=None, arrow=True):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    a = ' marker-end="url(#arrow)"' if arrow else ""
    return f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="{stroke}" stroke-width="{sw}"{d}{a}/>'


def elbow_down_then_right(x1, y1, x2, y2, **kw):
    my = (y1 + y2) / 2
    return (
        line(x1, y1, x1, my, arrow=False, **kw)
        + line(x1, my, x2, my, arrow=False, **kw)
        + line(x2, my, x2, y2, **kw)
    )


# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------


def build(annotated: bool) -> str:
    parts = []
    y = 0

    # ---- title -----------------------------------------------------------
    y += 48
    t, _ = text_block(W / 2, y, [TITLE], 30, INK, weight="700")
    parts.append(t)
    y += 30
    t, _ = text_block(W / 2, y, [SUBTITLE], 15.5, SUBINK)
    parts.append(t)
    y += 40

    # ---- Band A: sources ---------------------------------------------------
    band_top = y
    cols = 4
    rows = -(-len(SOURCES) // cols)
    gap = 20
    box_w = (CONTENT_W - (cols - 1) * gap) / cols
    box_h = 74
    header_h = 34
    band_h = header_h + rows * box_h + (rows - 1) * gap + 24

    style = BAND_STYLES["sources"]
    parts.append(rrect(MARGIN, band_top, CONTENT_W, band_h, 14, style["fill"], style["stroke"], sw=1.2))
    t, _ = text_block(MARGIN + 18, band_top + 24, [style["label"]], 14, SUBINK, weight="700", anchor="start")
    parts.append(t)

    bypass_source_xy = None
    for i, src in enumerate(SOURCES):
        col, row = i % cols, i // cols
        bx = MARGIN + 16 + col * (box_w + gap)
        by = band_top + header_h + row * (box_h + gap)
        parts.append(rrect(bx, by, box_w - 16, box_h, 10, "#ffffff", style["stroke"], sw=1.1))
        cx = bx + (box_w - 16) / 2
        name_lines = wrap(src["name"], box_w - 40, 14.5, bold=True)
        t, used = text_block(cx, by + 24, name_lines, 14.5, INK, weight="700")
        parts.append(t)
        grain_lines = wrap(src["grain"], box_w - 40, 12)
        t, _ = text_block(cx, by + 24 + used + 4, grain_lines, 12, SUBINK)
        parts.append(t)
        if src.get("bypass"):
            bypass_source_xy = (bx + box_w - 16 - 14, by + box_h)

    sources_bottom_y = band_top + band_h
    y = sources_bottom_y + 46

    # ---- Band B: pipeline ---------------------------------------------------
    band_top = y
    n = len(STAGES)
    gap = 20
    stage_w = (CONTENT_W - (n - 1) * gap) / n
    stage_h = 150 if annotated else 118
    strip_h = 46
    header_h = 30
    band_h = header_h + strip_h + 26 + stage_h + 20

    style = BAND_STYLES["pipeline"]
    parts.append(rrect(MARGIN, band_top, CONTENT_W, band_h, 14, style["fill"], style["stroke"], sw=1.2))
    t, _ = text_block(MARGIN + 18, band_top + 24, [style["label"]], 14, SUBINK, weight="700", anchor="start")
    parts.append(t)
    parts.append(line(MARGIN + CONTENT_W / 2, sources_bottom_y, MARGIN + CONTENT_W / 2, band_top))

    strip_y = band_top + header_h
    strip_x = MARGIN + 16
    strip_w = CONTENT_W - 32
    parts.append(rrect(strip_x, strip_y, strip_w, strip_h, 8, "#fffaf1", "#d8a866", sw=1, dash="4,3"))
    cfg_text = f'{CONFIG_STAGE["id"]}_{CONFIG_STAGE["name"]}  —  {CONFIG_STAGE["desc"]}'
    lines = wrap(cfg_text, strip_w - 40, 12.5, bold=False)
    t, _ = text_block(strip_x + strip_w / 2, strip_y + strip_h / 2 - (len(lines) - 1) * 8 + 4, lines, 12.5, "#7a4a10", italic=True)
    parts.append(t)

    stage_y = strip_y + strip_h + 26
    for i, st in enumerate(STAGES):
        sx = MARGIN + 16 + i * (stage_w + gap)
        parts.append(line(sx + (stage_w - 16) / 2, strip_y + strip_h, sx + (stage_w - 16) / 2, stage_y, stroke="#d8a866", sw=1, dash="3,3", arrow=False))
        parts.append(rrect(sx, stage_y, stage_w - 16, stage_h, 10, "#ffffff", style["stroke"], sw=1.1))
        cx = sx + (stage_w - 16) / 2
        label = f'{st["id"]}_{st["name"]}'
        t, _ = text_block(cx, stage_y + 24, [label], 15, INK, weight="700")
        parts.append(t)
        desc_lines = wrap(st["desc"], stage_w - 40, 12)
        t, used = text_block(cx, stage_y + 46, desc_lines, 12, SUBINK)
        parts.append(t)
        if annotated:
            rule_lines = wrap(st["rule"], stage_w - 40, 11.5)
            ry = stage_y + 46 + used + 14
            t, _ = text_block(cx, ry, rule_lines, 11.5, RULE_COLOR, italic=True)
            parts.append(t)
        if i < n - 1:
            parts.append(line(sx + stage_w - 16, stage_y + stage_h / 2, sx + stage_w, stage_y + stage_h / 2))

    pipeline_bottom_y = band_top + band_h
    y = pipeline_bottom_y + 46

    # ---- Band C: outputs -----------------------------------------------------
    band_top = y
    header_h = 30
    staging_h = 46
    out_h = 76
    cc_h = 0
    if annotated:
        cc_line_h = 12 * 1.35
        for note in CROSSCUTTING:
            cc_h += len(wrap(note, CONTENT_W - 80, 12)) * cc_line_h + 8
        cc_h += 8
    band_h = header_h + staging_h + 30 + out_h + 20 + cc_h
    style = BAND_STYLES["outputs"]
    parts.append(rrect(MARGIN, band_top, CONTENT_W, band_h, 14, style["fill"], style["stroke"], sw=1.2))
    t, _ = text_block(MARGIN + 18, band_top + 24, [style["label"]], 14, SUBINK, weight="700", anchor="start")
    parts.append(t)
    parts.append(line(MARGIN + CONTENT_W / 2, pipeline_bottom_y, MARGIN + CONTENT_W / 2, band_top))

    staging_w = 260
    staging_x = MARGIN + CONTENT_W / 2 - staging_w / 2
    staging_y = band_top + header_h
    parts.append(rrect(staging_x, staging_y, staging_w, staging_h, 8, "#ffffff", style["stroke"], sw=1.1))
    t, _ = text_block(staging_x + staging_w / 2, staging_y + staging_h / 2 + 4, ["build/staging/"], 13, INK, weight="700")
    parts.append(t)

    n_out = len(OUTPUTS)
    ogap = 24
    out_w = (CONTENT_W - 32 - (n_out - 1) * ogap) / n_out
    out_y = staging_y + staging_h + 30
    out_anchors = []
    for i, o in enumerate(OUTPUTS):
        ox = MARGIN + 16 + i * (out_w + ogap)
        parts.append(rrect(ox, out_y, out_w, out_h, 10, "#ffffff", style["stroke"], sw=1.1))
        cx = ox + out_w / 2
        t, _ = text_block(cx, out_y + 26, [o["name"]], 14, INK, weight="700")
        parts.append(t)
        d_lines = wrap(o["desc"], out_w - 36, 12)
        t, _ = text_block(cx, out_y + 48, d_lines, 12, SUBINK)
        parts.append(t)
        parts.append(line(staging_x + staging_w / 2, staging_y + staging_h, cx, out_y))
        out_anchors.append((cx, out_y + out_h))

    if annotated:
        cc_y = out_y + out_h + 16
        for note in CROSSCUTTING:
            lines_ = wrap(note, CONTENT_W - 80, 12, bold=False)
            t, used = text_block(MARGIN + CONTENT_W / 2, cc_y + 4, lines_, 12, "#2f6b4f", italic=True)
            parts.append(t)
            cc_y += used + 8

    outputs_bottom_y = band_top + band_h
    y = outputs_bottom_y + 46

    # ---- Band D: site ----------------------------------------------------
    band_top = y
    n_site = len(SITE_PAGES)
    gap = 20
    site_w = (CONTENT_W - (n_site - 1) * gap) / n_site
    site_h = 84
    header_h = 30
    band_h = header_h + site_h + 24
    style = BAND_STYLES["site"]
    parts.append(rrect(MARGIN, band_top, CONTENT_W, band_h, 14, style["fill"], style["stroke"], sw=1.2))
    t, _ = text_block(MARGIN + 18, band_top + 24, [style["label"]], 14, SUBINK, weight="700", anchor="start")
    parts.append(t)

    site_y = band_top + header_h
    bypass_target_xy = None
    for i, pg in enumerate(SITE_PAGES):
        px = MARGIN + 16 + i * (site_w + gap)
        parts.append(rrect(px, site_y, site_w - 16, site_h, 10, "#ffffff", style["stroke"], sw=1.1))
        cx = px + (site_w - 16) / 2
        t, _ = text_block(cx, site_y + 24, [pg["name"]], 14, INK, weight="700")
        parts.append(t)
        d_lines = wrap(pg["desc"], site_w - 40, 11.5)
        t, _ = text_block(cx, site_y + 46, d_lines, 11.5, SUBINK)
        parts.append(t)
        if pg.get("bypass"):
            bypass_target_xy = (cx, site_y)
        else:
            # connect from nearest output anchor (json for explorer/event/compare, csv for downloads)
            src_xy = out_anchors[1] if pg["name"] == "Downloads" else out_anchors[0]
            parts.append(elbow_down_then_right(src_xy[0], src_xy[1] + 6, cx, site_y))

    total_h = band_top + band_h + 60

    # ---- bypass arrow: IEM Radar -> Radar overlay --------------------------
    bypass_svg = ""
    if bypass_source_xy and bypass_target_xy:
        x1, y1 = bypass_source_xy
        x2, y2 = bypass_target_xy
        path_x = W - MARGIN + 34
        bypass_svg += (
            f'<path d="M {x1:.1f} {y1:.1f} C {path_x:.1f} {y1+40:.1f}, {path_x:.1f} {y2-60:.1f}, {x2:.1f} {y2:.1f}" '
            f'fill="none" stroke="#6b7d8f" stroke-width="1.6" stroke-dasharray="6,4" marker-end="url(#arrow-grey)"/>'
        )
        lbl_x = W - MARGIN + 46
        lbl_y = (y1 + y2) / 2
        t, _ = text_block(lbl_x, lbl_y, wrap(BYPASS_LABEL, 150, 11), 11, "#52606d", anchor="start", italic=True)
        bypass_svg += t
        total_w_extra = 210
    else:
        total_w_extra = 0

    # ---- footnote ----------------------------------------------------------
    foot, _ = text_block(MARGIN, total_h - 10, wrap(FOOTNOTE, CONTENT_W, 11), 11, "#8a94a0", anchor="start")

    view_w = W + total_w_extra
    body = "\n".join(p for p in parts if p) + bypass_svg + foot

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {view_w:.0f} {total_h:.0f}" role="img" aria-label="{esc(TITLE)}: {esc(SUBTITLE)}">
<title>{esc(TITLE)}</title>
<desc>{esc(SUBTITLE)}. Eight sources feed a five-stage pipeline governed by a single config file; the pipeline writes JSON and CSV outputs that the static site reads, except radar tiles, which the browser fetches live and which bypass the pipeline entirely.</desc>
<defs>
<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
<path d="M0,0 L10,5 L0,10 z" fill="{LINE}"/>
</marker>
<marker id="arrow-grey" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
<path d="M0,0 L10,5 L0,10 z" fill="#6b7d8f"/>
</marker>
</defs>
<rect x="0" y="0" width="{view_w:.0f}" height="{total_h:.0f}" fill="{BG}"/>
{body}
</svg>
'''
    return svg


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["basic", "annotated", "both"], default="both")
    ap.add_argument("--out-dir", default="docs")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.mode in ("basic", "both"):
        (out_dir / "dataflow.svg").write_text(build(annotated=False))
        print(f"wrote {out_dir / 'dataflow.svg'}")
    if args.mode in ("annotated", "both"):
        (out_dir / "dataflow-annotated.svg").write_text(build(annotated=True))
        print(f"wrote {out_dir / 'dataflow-annotated.svg'}")


if __name__ == "__main__":
    main()
